version: '3'

services:
  db:
    image: mysql:5.7
    container_name: servidor_dados
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: banco_de_dados
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - microservices-network
    restart: always

networks:
  microservices-network:
    driver: bridge

